dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: postgres
      pass: postgres
      dbname: dbtDB
      schema: public
